# Generated by Django 4.0 on 2022-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=400)),
                ('code_name', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
    ]
